// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package google.example;

public final class Game {
  private Game() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_example_RankList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_example_RankList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_example_Ranker_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_example_Ranker_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_example_Gamer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_example_Gamer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_example_Welecom_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_example_Welecom_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_example_GRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_example_GRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_example_GRequest_Player_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_example_GRequest_Player_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_example_GResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_example_GResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_example_GResponse_Player_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_example_GResponse_Player_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_example_GResponse_Result_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_example_GResponse_Result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ngame.proto\022\016google.example\"2\n\010RankList" +
      "\022&\n\006ranker\030\001 \003(\0132\026.google.example.Ranker" +
      "\"6\n\006Ranker\022\014\n\004name\030\001 \001(\t\022\r\n\005score\030\002 \001(\005\022" +
      "\017\n\007ranking\030\003 \001(\005\"!\n\005Gamer\022\014\n\004name\030\001 \001(\t\022" +
      "\n\n\002ip\030\002 \001(\t\"\301\001\n\007Welecom\022.\n\006status\030\001 \001(\0162" +
      "\036.google.example.Welecom.Status\0221\n\005ctype" +
      "\030\002 \001(\0162\".google.example.Welecom.ClientTy" +
      "pe\"0\n\006Status\022\010\n\004WAIT\020\000\022\t\n\005READY\020\001\022\021\n\rREA" +
      "DY_IS_HOST\020\002\"!\n\nClientType\022\010\n\004HOST\020\000\022\t\n\005" +
      "GUEST\020\001\"\302\002\n\010GRequest\0229\n\013messageType\030\001 \001(" +
      "\0162$.google.example.GRequest.MessageType\022" +
      "/\n\006player\030\002 \001(\0132\037.google.example.GReques" +
      "t.Player\022/\n\006select\030\003 \001(\0162\037.google.exampl" +
      "e.GRequest.Select\032\"\n\006Player\022\014\n\004name\030\001 \001(" +
      "\t\022\n\n\002ip\030\002 \001(\t\"?\n\013MessageType\022\n\n\006SELECT\020\000" +
      "\022\023\n\017HOST_GAME_START\020\001\022\017\n\013TIMEOUT_ACK\020\002\"4" +
      "\n\006Select\022\010\n\004NONE\020\000\022\010\n\004ROCK\020\001\022\013\n\007SCISSOR\020" +
      "\002\022\t\n\005PAPER\020\003\"\347\003\n\tGResponse\022:\n\013messageTyp" +
      "e\030\001 \001(\0162%.google.example.GResponse.Messa" +
      "geType\0220\n\006player\030\002 \003(\0132 .google.example." +
      "GResponse.Player\0226\n\013timeoutInfo\030\003 \001(\0162!." +
      "google.example.GResponse.Timeout\022\024\n\014time" +
      "outCount\030\004 \001(\005\022)\n\nhostPlayer\030\005 \001(\0132\025.goo" +
      "gle.example.Gamer\0220\n\006result\030\006 \001(\0132 .goog" +
      "le.example.GResponse.Result\032\"\n\006Player\022\014\n" +
      "\004name\030\001 \001(\t\022\n\n\002ip\030\002 \001(\t\032\'\n\006Result\022\016\n\006win" +
      "ner\030\001 \003(\t\022\r\n\005point\030\002 \001(\t\"W\n\013MessageType\022" +
      "\t\n\005START\020\000\022\013\n\007TIMEOUT\020\001\022\n\n\006RESULT\020\002\022\010\n\004D" +
      "RAW\020\003\022\t\n\005LEAVE\020\004\022\017\n\013CHANGE_HOST\020\005\"\033\n\007Tim" +
      "eout\022\007\n\003NOT\020\000\022\007\n\003YES\020\0012\305\001\n\016RspApplicatio" +
      "n\0229\n\005Login\022\025.google.example.Gamer\032\027.goog" +
      "le.example.Welecom0\001\022?\n\004Game\022\030.google.ex" +
      "ample.GRequest\032\031.google.example.GRespons" +
      "e(\0010\001\0227\n\004Rank\022\025.google.example.Gamer\032\030.g" +
      "oogle.example.RankListB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_google_example_RankList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_example_RankList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_example_RankList_descriptor,
        new java.lang.String[] { "Ranker", });
    internal_static_google_example_Ranker_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_example_Ranker_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_example_Ranker_descriptor,
        new java.lang.String[] { "Name", "Score", "Ranking", });
    internal_static_google_example_Gamer_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_example_Gamer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_example_Gamer_descriptor,
        new java.lang.String[] { "Name", "Ip", });
    internal_static_google_example_Welecom_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_example_Welecom_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_example_Welecom_descriptor,
        new java.lang.String[] { "Status", "Ctype", });
    internal_static_google_example_GRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_example_GRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_example_GRequest_descriptor,
        new java.lang.String[] { "MessageType", "Player", "Select", });
    internal_static_google_example_GRequest_Player_descriptor =
      internal_static_google_example_GRequest_descriptor.getNestedTypes().get(0);
    internal_static_google_example_GRequest_Player_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_example_GRequest_Player_descriptor,
        new java.lang.String[] { "Name", "Ip", });
    internal_static_google_example_GResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_example_GResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_example_GResponse_descriptor,
        new java.lang.String[] { "MessageType", "Player", "TimeoutInfo", "TimeoutCount", "HostPlayer", "Result", });
    internal_static_google_example_GResponse_Player_descriptor =
      internal_static_google_example_GResponse_descriptor.getNestedTypes().get(0);
    internal_static_google_example_GResponse_Player_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_example_GResponse_Player_descriptor,
        new java.lang.String[] { "Name", "Ip", });
    internal_static_google_example_GResponse_Result_descriptor =
      internal_static_google_example_GResponse_descriptor.getNestedTypes().get(1);
    internal_static_google_example_GResponse_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_example_GResponse_Result_descriptor,
        new java.lang.String[] { "Winner", "Point", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
