// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package google.example;

public interface GRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.example.GRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.example.GRequest.MessageType messageType = 1;</code>
   * @return The enum numeric value on the wire for messageType.
   */
  int getMessageTypeValue();
  /**
   * <code>.google.example.GRequest.MessageType messageType = 1;</code>
   * @return The messageType.
   */
  google.example.GRequest.MessageType getMessageType();

  /**
   * <code>.google.example.GRequest.Player player = 2;</code>
   * @return Whether the player field is set.
   */
  boolean hasPlayer();
  /**
   * <code>.google.example.GRequest.Player player = 2;</code>
   * @return The player.
   */
  google.example.GRequest.Player getPlayer();
  /**
   * <code>.google.example.GRequest.Player player = 2;</code>
   */
  google.example.GRequest.PlayerOrBuilder getPlayerOrBuilder();

  /**
   * <code>.google.example.GRequest.Select select = 3;</code>
   * @return The enum numeric value on the wire for select.
   */
  int getSelectValue();
  /**
   * <code>.google.example.GRequest.Select select = 3;</code>
   * @return The select.
   */
  google.example.GRequest.Select getSelect();
}
