// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package google.example;

public interface GResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.example.GResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.example.GResponse.MessageType messageType = 1;</code>
   * @return The enum numeric value on the wire for messageType.
   */
  int getMessageTypeValue();
  /**
   * <code>.google.example.GResponse.MessageType messageType = 1;</code>
   * @return The messageType.
   */
  google.example.GResponse.MessageType getMessageType();

  /**
   * <code>repeated .google.example.GResponse.Player player = 2;</code>
   */
  java.util.List<google.example.GResponse.Player> 
      getPlayerList();
  /**
   * <code>repeated .google.example.GResponse.Player player = 2;</code>
   */
  google.example.GResponse.Player getPlayer(int index);
  /**
   * <code>repeated .google.example.GResponse.Player player = 2;</code>
   */
  int getPlayerCount();
  /**
   * <code>repeated .google.example.GResponse.Player player = 2;</code>
   */
  java.util.List<? extends google.example.GResponse.PlayerOrBuilder> 
      getPlayerOrBuilderList();
  /**
   * <code>repeated .google.example.GResponse.Player player = 2;</code>
   */
  google.example.GResponse.PlayerOrBuilder getPlayerOrBuilder(
      int index);

  /**
   * <code>.google.example.GResponse.Timeout timeoutInfo = 3;</code>
   * @return The enum numeric value on the wire for timeoutInfo.
   */
  int getTimeoutInfoValue();
  /**
   * <code>.google.example.GResponse.Timeout timeoutInfo = 3;</code>
   * @return The timeoutInfo.
   */
  google.example.GResponse.Timeout getTimeoutInfo();

  /**
   * <code>int32 timeoutCount = 4;</code>
   * @return The timeoutCount.
   */
  int getTimeoutCount();

  /**
   * <code>.google.example.Gamer hostPlayer = 5;</code>
   * @return Whether the hostPlayer field is set.
   */
  boolean hasHostPlayer();
  /**
   * <code>.google.example.Gamer hostPlayer = 5;</code>
   * @return The hostPlayer.
   */
  google.example.Gamer getHostPlayer();
  /**
   * <code>.google.example.Gamer hostPlayer = 5;</code>
   */
  google.example.GamerOrBuilder getHostPlayerOrBuilder();

  /**
   * <code>.google.example.GResponse.Result result = 6;</code>
   * @return Whether the result field is set.
   */
  boolean hasResult();
  /**
   * <code>.google.example.GResponse.Result result = 6;</code>
   * @return The result.
   */
  google.example.GResponse.Result getResult();
  /**
   * <code>.google.example.GResponse.Result result = 6;</code>
   */
  google.example.GResponse.ResultOrBuilder getResultOrBuilder();
}
