// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package google.example;

/**
 * Protobuf type {@code google.example.RankList}
 */
public final class RankList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.example.RankList)
    RankListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RankList.newBuilder() to construct.
  private RankList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RankList() {
    ranker_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RankList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RankList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              ranker_ = new java.util.ArrayList<google.example.Ranker>();
              mutable_bitField0_ |= 0x00000001;
            }
            ranker_.add(
                input.readMessage(google.example.Ranker.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        ranker_ = java.util.Collections.unmodifiableList(ranker_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return google.example.Game.internal_static_google_example_RankList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return google.example.Game.internal_static_google_example_RankList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            google.example.RankList.class, google.example.RankList.Builder.class);
  }

  public static final int RANKER_FIELD_NUMBER = 1;
  private java.util.List<google.example.Ranker> ranker_;
  /**
   * <code>repeated .google.example.Ranker ranker = 1;</code>
   */
  @java.lang.Override
  public java.util.List<google.example.Ranker> getRankerList() {
    return ranker_;
  }
  /**
   * <code>repeated .google.example.Ranker ranker = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends google.example.RankerOrBuilder> 
      getRankerOrBuilderList() {
    return ranker_;
  }
  /**
   * <code>repeated .google.example.Ranker ranker = 1;</code>
   */
  @java.lang.Override
  public int getRankerCount() {
    return ranker_.size();
  }
  /**
   * <code>repeated .google.example.Ranker ranker = 1;</code>
   */
  @java.lang.Override
  public google.example.Ranker getRanker(int index) {
    return ranker_.get(index);
  }
  /**
   * <code>repeated .google.example.Ranker ranker = 1;</code>
   */
  @java.lang.Override
  public google.example.RankerOrBuilder getRankerOrBuilder(
      int index) {
    return ranker_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < ranker_.size(); i++) {
      output.writeMessage(1, ranker_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < ranker_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, ranker_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof google.example.RankList)) {
      return super.equals(obj);
    }
    google.example.RankList other = (google.example.RankList) obj;

    if (!getRankerList()
        .equals(other.getRankerList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRankerCount() > 0) {
      hash = (37 * hash) + RANKER_FIELD_NUMBER;
      hash = (53 * hash) + getRankerList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static google.example.RankList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static google.example.RankList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static google.example.RankList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static google.example.RankList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static google.example.RankList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static google.example.RankList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static google.example.RankList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static google.example.RankList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static google.example.RankList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static google.example.RankList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static google.example.RankList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static google.example.RankList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(google.example.RankList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code google.example.RankList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.example.RankList)
      google.example.RankListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return google.example.Game.internal_static_google_example_RankList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return google.example.Game.internal_static_google_example_RankList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              google.example.RankList.class, google.example.RankList.Builder.class);
    }

    // Construct using google.example.RankList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRankerFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (rankerBuilder_ == null) {
        ranker_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        rankerBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return google.example.Game.internal_static_google_example_RankList_descriptor;
    }

    @java.lang.Override
    public google.example.RankList getDefaultInstanceForType() {
      return google.example.RankList.getDefaultInstance();
    }

    @java.lang.Override
    public google.example.RankList build() {
      google.example.RankList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public google.example.RankList buildPartial() {
      google.example.RankList result = new google.example.RankList(this);
      int from_bitField0_ = bitField0_;
      if (rankerBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          ranker_ = java.util.Collections.unmodifiableList(ranker_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ranker_ = ranker_;
      } else {
        result.ranker_ = rankerBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof google.example.RankList) {
        return mergeFrom((google.example.RankList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(google.example.RankList other) {
      if (other == google.example.RankList.getDefaultInstance()) return this;
      if (rankerBuilder_ == null) {
        if (!other.ranker_.isEmpty()) {
          if (ranker_.isEmpty()) {
            ranker_ = other.ranker_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRankerIsMutable();
            ranker_.addAll(other.ranker_);
          }
          onChanged();
        }
      } else {
        if (!other.ranker_.isEmpty()) {
          if (rankerBuilder_.isEmpty()) {
            rankerBuilder_.dispose();
            rankerBuilder_ = null;
            ranker_ = other.ranker_;
            bitField0_ = (bitField0_ & ~0x00000001);
            rankerBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRankerFieldBuilder() : null;
          } else {
            rankerBuilder_.addAllMessages(other.ranker_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      google.example.RankList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (google.example.RankList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<google.example.Ranker> ranker_ =
      java.util.Collections.emptyList();
    private void ensureRankerIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        ranker_ = new java.util.ArrayList<google.example.Ranker>(ranker_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        google.example.Ranker, google.example.Ranker.Builder, google.example.RankerOrBuilder> rankerBuilder_;

    /**
     * <code>repeated .google.example.Ranker ranker = 1;</code>
     */
    public java.util.List<google.example.Ranker> getRankerList() {
      if (rankerBuilder_ == null) {
        return java.util.Collections.unmodifiableList(ranker_);
      } else {
        return rankerBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .google.example.Ranker ranker = 1;</code>
     */
    public int getRankerCount() {
      if (rankerBuilder_ == null) {
        return ranker_.size();
      } else {
        return rankerBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .google.example.Ranker ranker = 1;</code>
     */
    public google.example.Ranker getRanker(int index) {
      if (rankerBuilder_ == null) {
        return ranker_.get(index);
      } else {
        return rankerBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .google.example.Ranker ranker = 1;</code>
     */
    public Builder setRanker(
        int index, google.example.Ranker value) {
      if (rankerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRankerIsMutable();
        ranker_.set(index, value);
        onChanged();
      } else {
        rankerBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.example.Ranker ranker = 1;</code>
     */
    public Builder setRanker(
        int index, google.example.Ranker.Builder builderForValue) {
      if (rankerBuilder_ == null) {
        ensureRankerIsMutable();
        ranker_.set(index, builderForValue.build());
        onChanged();
      } else {
        rankerBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.example.Ranker ranker = 1;</code>
     */
    public Builder addRanker(google.example.Ranker value) {
      if (rankerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRankerIsMutable();
        ranker_.add(value);
        onChanged();
      } else {
        rankerBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .google.example.Ranker ranker = 1;</code>
     */
    public Builder addRanker(
        int index, google.example.Ranker value) {
      if (rankerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRankerIsMutable();
        ranker_.add(index, value);
        onChanged();
      } else {
        rankerBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.example.Ranker ranker = 1;</code>
     */
    public Builder addRanker(
        google.example.Ranker.Builder builderForValue) {
      if (rankerBuilder_ == null) {
        ensureRankerIsMutable();
        ranker_.add(builderForValue.build());
        onChanged();
      } else {
        rankerBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.example.Ranker ranker = 1;</code>
     */
    public Builder addRanker(
        int index, google.example.Ranker.Builder builderForValue) {
      if (rankerBuilder_ == null) {
        ensureRankerIsMutable();
        ranker_.add(index, builderForValue.build());
        onChanged();
      } else {
        rankerBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.example.Ranker ranker = 1;</code>
     */
    public Builder addAllRanker(
        java.lang.Iterable<? extends google.example.Ranker> values) {
      if (rankerBuilder_ == null) {
        ensureRankerIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ranker_);
        onChanged();
      } else {
        rankerBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .google.example.Ranker ranker = 1;</code>
     */
    public Builder clearRanker() {
      if (rankerBuilder_ == null) {
        ranker_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        rankerBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .google.example.Ranker ranker = 1;</code>
     */
    public Builder removeRanker(int index) {
      if (rankerBuilder_ == null) {
        ensureRankerIsMutable();
        ranker_.remove(index);
        onChanged();
      } else {
        rankerBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .google.example.Ranker ranker = 1;</code>
     */
    public google.example.Ranker.Builder getRankerBuilder(
        int index) {
      return getRankerFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .google.example.Ranker ranker = 1;</code>
     */
    public google.example.RankerOrBuilder getRankerOrBuilder(
        int index) {
      if (rankerBuilder_ == null) {
        return ranker_.get(index);  } else {
        return rankerBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .google.example.Ranker ranker = 1;</code>
     */
    public java.util.List<? extends google.example.RankerOrBuilder> 
         getRankerOrBuilderList() {
      if (rankerBuilder_ != null) {
        return rankerBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(ranker_);
      }
    }
    /**
     * <code>repeated .google.example.Ranker ranker = 1;</code>
     */
    public google.example.Ranker.Builder addRankerBuilder() {
      return getRankerFieldBuilder().addBuilder(
          google.example.Ranker.getDefaultInstance());
    }
    /**
     * <code>repeated .google.example.Ranker ranker = 1;</code>
     */
    public google.example.Ranker.Builder addRankerBuilder(
        int index) {
      return getRankerFieldBuilder().addBuilder(
          index, google.example.Ranker.getDefaultInstance());
    }
    /**
     * <code>repeated .google.example.Ranker ranker = 1;</code>
     */
    public java.util.List<google.example.Ranker.Builder> 
         getRankerBuilderList() {
      return getRankerFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        google.example.Ranker, google.example.Ranker.Builder, google.example.RankerOrBuilder> 
        getRankerFieldBuilder() {
      if (rankerBuilder_ == null) {
        rankerBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            google.example.Ranker, google.example.Ranker.Builder, google.example.RankerOrBuilder>(
                ranker_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        ranker_ = null;
      }
      return rankerBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.example.RankList)
  }

  // @@protoc_insertion_point(class_scope:google.example.RankList)
  private static final google.example.RankList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new google.example.RankList();
  }

  public static google.example.RankList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RankList>
      PARSER = new com.google.protobuf.AbstractParser<RankList>() {
    @java.lang.Override
    public RankList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RankList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RankList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RankList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public google.example.RankList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

