// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package google.example;

public interface RankListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.example.RankList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .google.example.Ranker ranker = 1;</code>
   */
  java.util.List<google.example.Ranker> 
      getRankerList();
  /**
   * <code>repeated .google.example.Ranker ranker = 1;</code>
   */
  google.example.Ranker getRanker(int index);
  /**
   * <code>repeated .google.example.Ranker ranker = 1;</code>
   */
  int getRankerCount();
  /**
   * <code>repeated .google.example.Ranker ranker = 1;</code>
   */
  java.util.List<? extends google.example.RankerOrBuilder> 
      getRankerOrBuilderList();
  /**
   * <code>repeated .google.example.Ranker ranker = 1;</code>
   */
  google.example.RankerOrBuilder getRankerOrBuilder(
      int index);
}
