// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package google.example;

public interface RankerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.example.Ranker)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 score = 2;</code>
   * @return The score.
   */
  int getScore();

  /**
   * <code>int32 ranking = 3;</code>
   * @return The ranking.
   */
  int getRanking();
}
