// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package google.example;

public interface WelecomOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.example.Welecom)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.example.Welecom.Status status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.google.example.Welecom.Status status = 1;</code>
   * @return The status.
   */
  google.example.Welecom.Status getStatus();

  /**
   * <code>.google.example.Welecom.ClientType ctype = 2;</code>
   * @return The enum numeric value on the wire for ctype.
   */
  int getCtypeValue();
  /**
   * <code>.google.example.Welecom.ClientType ctype = 2;</code>
   * @return The ctype.
   */
  google.example.Welecom.ClientType getCtype();
}
